services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: syb
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./sql:/docker-entrypoint-initdb.d

    backend:
        build: ./backend  # Ruta al directorio donde está tu Dockerfile y la app.js
        depends_on:
            - db
        ports:
            - "3000:3000"
        environment:
            DATABASE_URL: "postgres://postgres:1234@db:5432/syb"

    nginx:
        image: nginx:latest
        volumes:
            - ./src/html:/usr/share/nginx/html
            - ./src/js:/usr/share/nginx/html/js      # Mapea los archivos HTML
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mapea el archivo nginx.conf
        ports:
            - "80:80"
        depends_on:
            - backend

volumes:
    postgres_data:
